// Auth
export const AUTH_API_LOADING = 'AUTH_API_LOADING';

export const ON_CHANGE_INPUT = 'ON_CHANGE_INPUT';
export const CHANGE_LOGIN_CURRENT_VIEW = 'CHANGE_LOGIN_CURRENT_VIEW';
export const CHANGE_SIGNUP_CURRENT_VIEW = 'CHANGE_SIGNUP_CURRENT_VIEW';

export const SUCCESS_REGISTER_USER = 'SUCCESS_REGISTER_USER';
export const FAILED_REGISTER_USER = 'FAILED_REGISTER_USER';

export const SUCCESS_LOGIN_USER = 'SUCCESS_LOGIN_USER';
export const FAILED_LOGIN_USER = 'FAILED_LOGIN_USER';

export const SUCCESS_REMOVE_ACCESS_TOKEN = 'SUCCESS_REMOVE_ACCESS_TOKEN';
export const FAILED_REMOVE_ACCESS_TOKEN = 'FAILED_REMOVE_ACCESS_TOKEN';

export const SUCCESS_REMOVE_REFRESH_TOKEN = 'SUCCESS_REMOVE_REFRESH_TOKEN';
export const FAILED_REMOVE_REFRESH_TOKEN = 'FAILED_REMOVE_REFRESH_TOKEN';

// home
export const HOME_API_LOADING = 'HOME_API_LOADING';

export const HOME_BUTTON_LOADING = 'HOME_BUTTON_LOADING';

export const SUCCESS_GET_HOME_PAGE_GAMES = 'SUCCESS_GET_HOME_PAGE_GAMES';
export const FAILED_GET_HOME_PAGE_GAMES = 'FAILED_GET_HOME_PAGE_GAMES';

export const ON_CHANGE_SEARCH_KEY = 'ON_CHANGE_SEARCH_KEY';

export const SUCCESS_GET_SEARCH_GAMES = 'SUCCESS_GET_SEARCH_GAMES';
export const FAILED_GET_SEARCH_GAMES = 'FAILED_GET_SEARCH_GAMES';

// profile
export const GENERAL_API_LOADING = 'GENERAL_API_LOADING';

export const SUCCESS_GET_USER_PROFILE_INFO = 'SUCCESS_GET_USER_PROFILE_INFO';
export const FAILED_GET_USER_PROFILE_INFO = 'FAILED_GET_USER_PROFILE_INFO';

export const SET_IMAGE_URL = 'SET_IMAGE_URL';

export const HANDLE_CROP_CHANGE = 'HANDLE_CROP_CHANGE';

export const ON_CLOSE_MODAL = 'ON_CLOSE_MODAL';

export const SET_CROPPED_FILE = 'SET_CROPPED_FILE';

export const PROFILE_API_LOADING = 'PROFILE_API_LOADING';

export const SUCCESS_UPDATE_PROFILE_PICTURE = 'SUCCESS_UPDATE_PROFILE_PICTURE';
export const FAILED_UPDATE_PROFILE_PICTURE = 'FAILED_UPDATE_PROFILE_PICTURE';

export const BUTTON_PROFILE_NEW_OFFER_LOADING = 'BUTTON_PROFILE_NEW_OFFER_LOADING';

export const SUCCESS_GET_PROFILE_OFFERS = 'SUCCESS_GET_PROFILE_OFFERS';
export const FAILED_GET_PROFILE_OFFERS = 'FAILED_GET_PROFILE_OFFERS';

export const PROFILE_NEW_OFFER_LOADING = 'PROFILE_NEW_OFFER_LOADING';

export const SUCCESS_GET_ALL_GAMES = 'SUCCESS_GET_ALL_GAMES';
export const FAILED_GET_ALL_GAMES = 'FAILED_GET_ALL_GAMES';

export const SUCCESS_SEARCH_GAMES = 'SUCCESS_SEARCH_GAMES';
export const FAILED_SEARCH_GAMES = 'FAILED_SEARCH_GAMES';

export const SELECT_GAME = 'SELECT_GAME';

export const SELECT_REGION = 'SELECT_REGION';

export const CHANGE_PRICE = 'CHANGE_PRICE';

export const TOGGLE_DONATE = 'TOGGLE_DONATE';

export const TOGGLE_DONATION_AMOUNT = 'TOGGLE_DONATION_AMOUNT';

export const ADD_PRODUCT_KEY = 'ADD_PRODUCT_KEY';

export const REMOVE_PRODUCT_KEY = 'REMOVE_PRODUCT_KEY';

export const CHANGE_PRODUCT_KEY = 'CHANGE_PRODUCT_KEY';

export const ACCEPTED_FILE_NAME = 'ACCEPTED_FILE_NAME';

export const GET_PROGRESS_VALUE = 'GET_PROGRESS_VALUE';
export const SUCCESS_DOCUMENT_UPLOAD = 'SUCCESS_DOCUMENT_UPLOAD';
export const FAILED_DOCUMENT_UPLOAD = 'FAILED_DOCUMENT_UPLOAD';

export const SUCCESS_CREATE_NEW_OFFER = 'SUCCESS_CREATE_NEW_OFFER';
export const FAILED_CREATE_NEW_OFFER = 'FAILED_CREATE_NEW_OFFER';

export const SUCCESS_PUBLISH_NEW_OFFER = 'SUCCESS_PUBLISH_NEW_OFFER';
export const FAILED_PUBLISH_NEW_OFFER = 'FAILED_PUBLISH_NEW_OFFER';

export const SUCCESS_GET_UPLOADED_DOCUMENTS = 'SUCCESS_GET_UPLOADED_DOCUMENTS';
export const FAILED_GET_UPLOADED_DOCUMENTS = 'FAILED_GET_UPLOADED_DOCUMENTS';

export const SUCCESS_DELETE_UPLOADED_DOCUMENT = 'SUCCESS_DELETE_UPLOADED_DOCUMENT';
export const FAILED_DELETE_UPLOADED_DOCUMENT = 'FAILED_DELETE_UPLOADED_DOCUMENT';

export const SET_OFFER_STATUS = 'SET_OFFER_STATUS';

export const RESET_OFFER_STATUS = 'RESET_OFFER_STATUS';

export const PROFILE_PURCHASES_LOADING = 'PROFILE_PURCHASES_LOADING';

export const SUCCESS_GET_PURCHASES = 'SUCCESS_GET_PURCHASES';
export const FAILED_GET_PURCHASES = 'FAILED_GET_PURCHASES';

export const PROFILE_PURCHASE_DETAIL_LOADING = 'PROFILE_PURCHASE_DETAIL_LOADING';

export const SUCCESS_GET_PURCHASE_DETAIL = 'SUCCESS_GET_PURCHASE_DETAIL';
export const FAILED_GET_PURCHASE_DETAIL = 'FAILED_GET_PURCHASE_DETAIL';

export const WALLET_LOADING = 'WALLET_LOADING';

export const SUCCESS_GET_TRANSACTIONS = 'SUCCESS_GET_TRANSACTIONS';
export const FAILED_GET_TRANSACTIONS = 'FAILED_GET_TRANSACTIONS';

export const OFFER_DETAIL_LOADING = 'OFFER_DETAIL_LOADING';

export const SUCCESS_GET_OFFER_DETAIL = 'SUCCESS_GET_OFFER_DETAIL';
export const FAILED_GET_OFFER_DETAIL = 'FAILED_GET_OFFER_DETAIL';

// product
export const PRODUCT_API_LOADING = 'PRODUCT_API_LOADING';

export const SUCCESS_GET_PRODUCT_INFO = 'SUCCESS_GET_PRODUCT_INFO';
export const FAILED_GET_PRODUCT_INFO = 'FAILED_GET_PRODUCT_INFO';

export const SUCCESS_GET_CURRENT_SELLERS = 'SUCCESS_GET_CURRENT_SELLERS';
export const FAILED_GET_CURRENT_SELLERS = 'FAILED_GET_CURRENT_SELLERS';

export const ADD_TO_CART = 'ADD_TO_CART';

export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';

export const REMOVE_OFFER = 'REMOVE_OFFER';

export const RESET_QUANTITY_COUNT_ERROR = 'RESET_QUANTITY_COUNT_ERROR';

// checkout
export const CHECKOUT_API_LOADING = 'CHECKOUT_API_LOADING';

export const SUCCESS_CREATE_SOURCE = 'SUCCESS_CREATE_SOURCE';
export const FAILED_CREATE_SOURCE = 'FAILED_CREATE_SOURCE';

export const CHANGE_CARD_DETAIL = 'CHANGE_CARD_DETAIL';

export const CHANGE_ADDRESS1 = 'CHANGE_ADDRESS1';
export const CHANGE_ADDRESS2 = 'CHANGE_ADDRESS2';
export const CHANGE_COUNTRY = 'CHANGE_COUNTRY';
export const CHANGE_CITY = 'CHANGE_CITY';
export const CHANGE_POSTAL_CODE = 'CHANGE_POSTAL_CODE';

export const SUCCESS_HANDLE_PAYMENT = 'SUCCESS_HANDLE_PAYMENT';
export const FAILED_HANDLE_PAYMENT = 'FAILED_HANDLE_PAYMENT';

export const RESET_SHIPPING_CART = 'RESET_SHIPPING_CART';

export const SUCCESS_PAYMENT_CHECK = 'SUCCESS_PAYMENT_CHECK';
export const FAILED_PAYMENT_CHECK = 'FAILED_PAYMENT_CHECK';

export const SUCCESS_GET_PRODUCT = 'SUCCESS_GET_PRODUCT';
export const FAILED_GET_PRODUCT = 'FAILED_GET_PRODUCT';